### ISSUE TITLE
突然有一天switch_hosts打不开了，不知道是不是因为电脑上装了python环境导致的？

### ISSUE THREAD

**Issue by kevinHuang211** [oldj/SwitchHosts#100]
最近打不开switchhosts,报以下错误：
Running scripts
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "D:\AliDrive\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "D:\AliDrive\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "D:\studio\SwitchHosts\dist\build\pyi.win32\SwitchHosts\out00-PYZ.pyz\wx", line 45, in <module>
  File "D:\AliDrive\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "D:\AliDrive\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "D:\studio\SwitchHosts\dist\build\pyi.win32\SwitchHosts\out00-PYZ.pyz\wx._core", line 4, in <module>
  File "D:\AliDrive\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 409, in importHook
ImportError: No module named _core_
RC: -1 from SwitchHosts
OK.
Deactivating activation context
Releasing activation context
Done
Back to parent...
Freeing status for C:\Users\asus\Downloads\SwitchHosts_v0.2.2.1798_debug\SwitchHosts_debug.exe

**Comment by KnightVan** [comment]
应该不是，我的工作机子上运行的就是switchhost，有安装python，正常运行。

**Comment by oldj** [comment]
Python 版本已经不维护了，试试用 Electron 打包的 [v3.2](https://github.com/oldj/SwitchHosts/releases/tag/v3.2.0) 版？
