### ISSUE TITLE
启动 Switchhost 时弹窗报错

### ISSUE THREAD

**Issue by oodzchen** [oldj/SwitchHosts#286]
### Description / 描述

启动时自动弹出报错窗口，消息如下：

> A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/main.js:36:16)
    at App.<anonymous> (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/main.js:152:5)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:194:7)

### How to reproduce / 重现步骤

打开 Switchhost ，重启 Mac 系统，再次手动打开 Switchhost，报错

**Comment by breakinferno** [comment]
me too

**Comment by ursulashan** [comment]
me too

**Comment by CHENTINGYU** [comment]
怎么解决啊

**Comment by CHENTINGYU** [comment]
我也是这种情况，windows

**Comment by oodzchen** [comment]
@CHENTINGYU 有没有试试卸载了然后安装最新版本，记得用管理员身份打开试试。我用的是macOS，具体也忘了怎么解决的了，已经很久没有这个软件了
