### ISSUE TITLE
error at launch

### ISSUE THREAD

**Issue by damelco** [oldj/SwitchHosts#366]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Windows 7

### SwitchHosts! Version / SwitchHosts! 版本
SwitchHosts-win32-x64_v3.3.12.5349.zip

### Description / 描述
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE 127.0.01:50761
  at Object.exports._errnoException (util.js:1024:11)
  at exports._exceptionWithHostPort (util.js:1047:20)
  at Server.setupListenHandle [as _listen2] (net.js:1319:14)
  at listenInCluster (net.js:1367:12)
  at doListen (net.js:1493:7)
  at _combinedTickCallback (internaVprocess/next_tick.js:141:11)
  at process._tickCallback (interna/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:607:11)
  at startup (bootstrap_node.js:167:16)
  at bootstrap_node.js:589:3 

### How to reproduce / 重现步骤
launch it!

**Comment by lzskyline** [comment]
一样  应该是Alfred的锅, 不影响使用

**Comment by oldj** [comment]
这是给 Alfred 等使用的 HTTP API 服务，在有些环境下会启动失败，不影响正常使用。现在的版本中这个服务默认关闭，有需要的用户可以在设置中手动开启。
