### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Jiafan** [oldj/SwitchHosts#483]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
macOS Catalina
version:10.15.6

### SwitchHosts! Version / SwitchHosts! 版本
我尝试了2个不同版本，均出现问题
3.5.4.5517
3.5.3.5514

### Description / 描述
```
Uncaught Exception:
Error: callback can only be called for once
    at Object.module.<computed> [as getAllDisplays] (electron/js2c/browser_init.js:6737:30)
    at ensureWindowVisibleOnSomeDisplay (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:58:28)
    at validateState (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:77:7)
    at module.exports (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:165:3)
    at createWindow (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/main.js:43:25)
    at App.<anonymous> (/Applications/SwitchHosts!.app/Contents/Resources/app.asar/main.js:194:5)
    at App.emit (events.js:203:13)
```
<img width="532" alt="Screen Shot 2020-07-23 at 7 27 35 AM" src="https://user-images.githubusercontent.com/10692668/88239129-0e0bf400-ccb6-11ea-9f51-1bb8a43752ae.png">

### How to reproduce / 重现步骤
安装首次启动，正常使用，电脑重启后，再次启动，启动失败，弹窗报错，报错内容如 描述
后续无法正常启动，重启也无济于事

**Comment by joostshao** [comment]
+1
看起来和多屏幕相关

**Comment by programluo** [comment]
+1
多屏幕相关，关掉多屏幕就好了

**Comment by oldj** [comment]
@joostshao @programluo 是指多显示器吗？

**Comment by ice-tong** [comment]
> @joostshao @programluo 是指多显示器吗？

是的，外接了个显示器就打不开报这个错误，把外接显示器拔掉就可以打开了。
