### ISSUE TITLE
打开程序闪退

### ISSUE THREAD

**Issue by stepbystep2** [oldj/SwitchHosts#590]
### System (Mac, Windows 7/8/10, Linux) / 操作系统
Ubuntu 20.04

### SwitchHosts! Version / SwitchHosts! 版本
4.0.1.6051

### Description / 描述
状态栏程序图标还在，但打开程序会闪退
![2021-05-13 14-27-43 的屏幕截图](https://user-images.githubusercontent.com/22957642/118087503-3ce78800-b3f8-11eb-8b11-960e159e95da.png)
```
data db: /home/wzy/.SwitchHosts/data
config db: /home/wzy/.SwitchHosts/config
VERSION: 4.0.1.6051
isDev:  false
Error: ERR_FAILED (-2) loading 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html#/find'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html#/find'
}
Error: ERR_FAILED (-2) loading 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html'
}
Error: ERR_FAILED (-2) loading 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html#/tray'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'file:///opt/SwitchHosts/resources/app.asar/renderer/index.html#/tray'
}
```

### How to reproduce / 重现步骤
1. 打开程序
2. 让电脑睡眠
3. 打开程序

**Comment by stepbystep2** [comment]
电脑重启之后程序可以正常启动了。
