### ISSUE TITLE
某天突然不能用了

### ISSUE THREAD

**Issue by smlrx1** [oldj/SwitchHosts#62]
Windows7下只有右下角小图标，单击、双击、右键小图标均无反应。搜索硬盘后删除相关崩溃日志才能继续使用……

**Comment by Xiongpq** [comment]
我的也是这个问题，建议加个错误日志功能

**Comment by agclqq** [comment]
我也遇到这个问题了，XP和win8.1均是此问题。

**Comment by weimy-wei** [comment]
我是win8.1  初安装系统是OK的，更新补丁后就无法打开了，出现过一次，又重装系统后确认是这个问题。

**Comment by BaboonWong** [comment]
我WIN10也遇到了这种问题了。

**Comment by smlrx1** [comment]
我的情况是host文件里混入了其他编码的字符，比如说utf-8之类的。
用ansi编码重建host就行。
我现在是把汉字等可能涉及其他编码的文字删除，再用ultraedit进行文字编码转换后在粘贴到host里。
btw：我也是win10，至今没什么问题






在 2015-10-28 18:58:17，"WangXinYuan" <notifications@github.com> 写道：


我WIN10也遇到了这种问题了。

**Comment by Himer** [comment]
同样 错误日志
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "D:\EverBox\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "D:\EverBox\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "D:\studio\SwitchHosts\dist\build\pyi.win32\SwitchHosts\out00-PYZ.pyz\wx", line 45, in <module>
  File "D:\EverBox\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "D:\EverBox\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "D:\studio\SwitchHosts\dist\build\pyi.win32\SwitchHosts\out00-PYZ.pyz\wx._core", line 4, in <module>
  File "D:\EverBox\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 409, in importHook
ImportError: No module named _core_
